### ISSUE TITLE
Pick scala style configuration

### ISSUE THREAD

**Issue by maxhutch** [CitrineInformatics/citrine-style#2]
Right now, we have the default config.  We should tune it.  Here are my requests:
- Allow `return` (for multiple return locations, e.g. returning from within nested loops)
- Allow methods longer than 50 lines.   Some of the math stuff needs more space than that and would get incoherent if sharded too far.
- Header with license?

We could also allow style checking escapes, e.g.:

```
// scalastyle:off
...
// naughty stuff
...
// scalastyle:on
```

(from scalastyle docs)

**Comment by kjaym** [comment]
I'm okay with the first two. For the third, are you suggesting that we make it so that the license does _not_ need to be in the header? I don't think that we need it there.

Also +1 on the scalastyle:[on,off] ... we do the same for java.

**Comment by sparadiso** [comment]
Yeah I'm not sure we need a license on much (any?) of our current code.
Otherwise I'm happy with these.

**Comment by maxhutch** [comment]
Fine with me.  I'll open a PR with these changes.
